# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('max_points', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListShipInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('stats', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='listshipinclusion',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwing.Ship'),
        ),
        migrations.AddField(
            model_name='listshipinclusion',
            name='xlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwing.List'),
        ),
        migrations.AddField(
            model_name='list',
            name='ships',
            field=models.ManyToManyField(through='xwing.ListShipInclusion', to='xwing.Ship'),
        ),
    ]
